name: presensi_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  fluttertoast: ^8.2.2
  shared_preferences: ^2.1.2
  camera: ^0.10.5+4
  provider: ^6.0.5
  http: ^1.1.0
  permission_handler: ^10.4.5
  audioplayers: ^5.1.0
  flutter_html: ^3.0.0-beta.2
  intl: ^0.18.1
  rxdart: ^0.27.7
  path_provider: ^2.1.1
  input_with_keyboard_control: ^1.0.8
  flutter_launcher_icons: "^0.13.1"
  change_app_package_name: ^1.1.0
  wakelock_plus: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/audios/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/iconapp2.png"
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
